### ISSUE TITLE
Road drawing routine

### ISSUE THREAD

**Issue by spec-chum** [dpt/ChaseHQ#1]
Possibly doesn't help, but I disassembled this years ago - I thought I might have the file still, but can't find it.

But I can remember the road drawing routine is stack based, with PUSH's and POP's and was located around the $BC00 area.

Look for groups of:
```
LD  ($xxxx), HL
LD SP, HL
POP DE
POP BC
EXX
POP AF
```
type sections.

Maybe this helps?

**Comment by dpt** [comment]
Magic, will do!

**Comment by dpt** [comment]
$BC3E is the screen copy routine. It blits the back buffer at $F000..$FFFF to the main screen once it's complete. It matches your description. Doesn't draw any roads though. The road drawing code is somewhere around $C551.

**Comment by spec-chum** [comment]
> $BC3E is the screen copy routine. It blits the back buffer at $F000..$FFFF to the main screen once it's complete. It matches your description. Doesn't draw any roads though. The road drawing code is somewhere around $C551.

Ah my bad, sorry - I remembered it was stack based, but thought that was the road.

Sorry about that,

**Comment by dpt** [comment]
No problem :-)
